In [32]:
import numpy as np
import math

In [2]:
def knn(data, query, k):
    dist_and_index = np.array([])
    for i in data

SyntaxError: unexpected EOF while parsing (<ipython-input-2-4b7ab699bedf>, line 2)

In [11]:
a = np.array([])
a = np.append(a, [1, 2, 3], axis=0)
a.reshape(1, 3)
a

array([1., 2., 3.])

In [16]:
reg_data = np.array([
       [65.75, 112.99],
       [71.52, 136.49],
       [69.40, 153.03],
       [68.22, 142.34],
       [67.79, 144.30],
       [68.70, 123.30],
       [69.80, 141.49],
       [70.01, 136.46],
       [67.90, 112.37],
       [66.49, 127.45],
    ])

In [17]:
reg_data[:, :-1]

array([[65.75],
       [71.52],
       [69.4 ],
       [68.22],
       [67.79],
       [68.7 ],
       [69.8 ],
       [70.01],
       [67.9 ],
       [66.49]])

In [18]:
for i in reg_data:
    print(i)

[ 65.75 112.99]
[ 71.52 136.49]
[ 69.4  153.03]
[ 68.22 142.34]
[ 67.79 144.3 ]
[ 68.7 123.3]
[ 69.8  141.49]
[ 70.01 136.46]
[ 67.9  112.37]
[ 66.49 127.45]


In [19]:
for index, ex in enumerate(reg_data):
    print(index, ex)

0 [ 65.75 112.99]
1 [ 71.52 136.49]
2 [ 69.4  153.03]
3 [ 68.22 142.34]
4 [ 67.79 144.3 ]
5 [ 68.7 123.3]
6 [ 69.8  141.49]
7 [ 70.01 136.46]
8 [ 67.9  112.37]
9 [ 66.49 127.45]


In [20]:
index = 3
dist = 5
np.array([index, dist])

array([3, 5])

In [23]:
np.sort(reg_data[:, -1], axis=0)

array([112.37, 112.99, 123.3 , 127.45, 136.46, 136.49, 141.49, 142.34,
       144.3 , 153.03])

In [24]:
arr = np.array([[11, 12, 13 , 22], [21, 7, 23, 14], [31, 10, 33, 7]])
arr

array([[11, 12, 13, 22],
       [21,  7, 23, 14],
       [31, 10, 33,  7]])

In [28]:
arr[:, 1]

array([12,  7, 10])

In [29]:
arr[:, 1].argsort()

array([1, 2, 0])

In [30]:
arr[np.array([1, 2, 0])]

array([[21,  7, 23, 14],
       [31, 10, 33,  7],
       [11, 12, 13, 22]])

In [33]:
def distance(a, b):
    dist = 0
    for i in range(len(a)):
        dist = dist + ((a[i] - b[i]) ** 2)
    dist = math.sqrt(dist)
    return dist

In [54]:
dist_and_index = np.array([[]])
x = reg_data[:, :-1]
y = reg_data[:, -1]
print(x)
print(y)

[[65.75]
 [71.52]
 [69.4 ]
 [68.22]
 [67.79]
 [68.7 ]
 [69.8 ]
 [70.01]
 [67.9 ]
 [66.49]]
[112.99 136.49 153.03 142.34 144.3  123.3  141.49 136.46 112.37 127.45]


In [57]:
query = np.array([60])
for index, i in enumerate(x):
    dist = distance(i, query)
    dist_and_index = np.append(dist_and_index, np.array([[index, dist]]), axis=0)
dist_and_index

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 0 and the array at index 1 has size 2

In [37]:
dist_and_index.size

20

In [38]:
reg_data.size

20

In [45]:
distance(query, x[1, :])

11.519999999999996

In [42]:
x[0, :]

array([65.75])

In [53]:
a = np.array([[3, 5]])
np.append(a, [[3, 5]], axis=0)

array([[3, 5],
       [3, 5]])

In [63]:
a = np.array([])
a = np.append(a, [1, 2], axis=0)
a

array([1., 2.])

In [65]:
np.append([a], [[3, 4]], axis=0)

array([[1., 2.],
       [3., 4.]])

In [67]:
b = np.array([[]])
b = np.append(b, [[3, 4]])
b

array([3., 4.])

In [69]:
np.append(b, [[1, 2]])

array([3., 4., 1., 2.])

In [72]:
arr = np.array([])
arr = np.append(arr, [])
arr

array([], dtype=float64)

In [73]:
arr = []
arr.append((0, 10))
arr

[(0, 10)]

In [75]:
arr.append((1, 20))
arr

[(0, 10), (1, 20), (1, 20)]

In [86]:
c = np.array([])
c = np.append(c, [1, 10])
c

array([ 1., 10.])

In [87]:
c = np.append([c], [[2, 20]], axis=0)
c

array([[ 1., 10.],
       [ 2., 20.]])

In [89]:
c = np.append(c, [[3, 30]], axis=0)
c

array([[ 1., 10.],
       [ 2., 20.],
       [ 3., 30.]])

In [90]:
c.append([4, 40])
c

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [91]:
query = np.array([60])
dist_and_index = []
for index, i in enumerate(x):
    dist = distance(i, query)
    dist_and_index.append([index, dist])
dist_and_index

[[0, 5.75],
 [1, 11.519999999999996],
 [2, 9.400000000000006],
 [3, 8.219999999999999],
 [4, 7.790000000000006],
 [5, 8.700000000000003],
 [6, 9.799999999999997],
 [7, 10.010000000000005],
 [8, 7.900000000000006],
 [9, 6.489999999999995]]

In [92]:
dist_and_index = np.array(dist_and_index)
sorted_array = dist_and_index[dist_and_index[:, 1].argsort()]
sorted_array

array([[ 0.  ,  5.75],
       [ 9.  ,  6.49],
       [ 4.  ,  7.79],
       [ 8.  ,  7.9 ],
       [ 3.  ,  8.22],
       [ 5.  ,  8.7 ],
       [ 2.  ,  9.4 ],
       [ 6.  ,  9.8 ],
       [ 7.  , 10.01],
       [ 1.  , 11.52]])

In [94]:
first_k = sorted_array[:3, 0]
first_k

array([0., 9., 4.])

In [95]:
first_k[np.array([2, 0, 1])]

array([4., 0., 9.])

In [97]:
print(x)
print(dist_and_index)

[[65.75]
 [71.52]
 [69.4 ]
 [68.22]
 [67.79]
 [68.7 ]
 [69.8 ]
 [70.01]
 [67.9 ]
 [66.49]]
[[ 0.    5.75]
 [ 1.   11.52]
 [ 2.    9.4 ]
 [ 3.    8.22]
 [ 4.    7.79]
 [ 5.    8.7 ]
 [ 6.    9.8 ]
 [ 7.   10.01]
 [ 8.    7.9 ]
 [ 9.    6.49]]


In [105]:
first_k = first_k.astype('int64')
first_k

array([0, 9, 4])

In [107]:
labels = np.array([])
for i in first_k:
    labels = np.append(labels, x[i])
labels

array([65.75, 66.49, 67.79])

In [100]:
x[0]

array([65.75])

In [103]:
for i in first_k:
    print(i)

0.0
9.0
4.0


In [108]:
np.mean(labels)

66.67666666666668

In [113]:
dist_and_index = np.empty((0, 2))
dist_and_index = np.append(dist_and_index, [0, 10])
dist_and_index

array([ 0., 10.])

In [115]:
dist_and_index = np.empty((0, 2))
for index, i in enumerate(x):
    dist = distance(i, query)
    dist_and_index = np.append(dist_and_index, [[index, dist]], axis=0)
dist_and_index

array([[ 0.  ,  5.75],
       [ 1.  , 11.52],
       [ 2.  ,  9.4 ],
       [ 3.  ,  8.22],
       [ 4.  ,  7.79],
       [ 5.  ,  8.7 ],
       [ 6.  ,  9.8 ],
       [ 7.  , 10.01],
       [ 8.  ,  7.9 ],
       [ 9.  ,  6.49]])